### ISSUE TITLE
Add support for dual wield (offhand dps)

### ISSUE THREAD

**Issue by farigiss** [Necroskillz/StatWeightScore#17]
I get this error whenever I mouse over an item in my bags or equipped.

Message: ...e\AddOns\StatWeightScore\StatWeightScore_Options.lua:227: attempt to index a nil value
Time: 01/05/15 21:03:26
Count: 1
Stack: (tail call): ?
[C]: ?
...e\AddOns\StatWeightScore\StatWeightScore_Options.lua:227: in function `SetupSpecWeightOptions'
...e\AddOns\StatWeightScore\StatWeightScore_Options.lua:357: in function `func'
Interface\FrameXML\UIDropDownMenu.lua:748: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

**Comment by Necroskillz** [comment]
this shouldn't happen when hovering over items.

can you post your config (located at WTF/Account/<account_name>/SavedVariables/StatWeightScore.lua)?

**Comment by Necroskillz** [comment]
I think I found the problem. You probably used the import feature and there is a stat that doesn't map to the addon stats. Not sure which one it is, so please send me the config so I can update it. In the meantime I will add a fix to prevent this behavior.

**Comment by farigiss** [comment]
http://pastebin.com/nX0pv4cf

Looks like it's probably wohdps (weapon offhand dps) It's fairly important to fury warriors and I think also enhancement shamans. Would you consider adding this stat?

**Comment by Necroskillz** [comment]
Yes, I will add it. Only issue will be weapons that are one-hand (not specifically mainhand or offhand). I will need to display mainhand score and offhand score, and compare them to respective equipped items. But it shouldn't be a big problem.

**Comment by Necroskillz** [comment]
This is what i got:
Offhand score will display only if
- offhand DPS stat is specified
- and at least one one-handed weapon is equipped

since i think it's useless to compare one-hand to two-hand weapons directly. it will not be role of this addon to help you decide between 2h and dual wield. (everyone should make this decision before deciding what weights to use). Casters will need to add up onehand+offhand vs staff.

![dual_wield](https://cloud.githubusercontent.com/assets/346477/5629056/88106ec8-95af-11e4-8174-40967f4004b4.jpg)

**Comment by Necroskillz** [comment]
closing this for now. new version is up. please check it out, and create a new issue if there is any additional feedback.
